# Generated by Django 4.2.18 on 2026-06-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Id do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe o nome do Instrutor', max_length=70)),
                ('data_nascimento', models.DateField(blank=True, help_text='Informe a data de nascimento do instrutor', null=True)),
                ('ddd', models.CharField(help_text='Informe o DDD do instrutor', max_length=3)),
                ('telefone', models.CharField(help_text='Informe o telefone do instrutor', max_length=9)),
                ('codigo_titulo', models.IntegerField(help_text='Informe o código do título do instrutor')),
            ],
        ),
    ]
