# Generated by Django 6.0.6 on 2026-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codigo', models.AutoField(help_text='Código do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do aluno', max_length=100)),
            ],
        ),
    ]
